#set service port
server:
  port: 7070

#set application name
spring:
  application:
    name: provider-service

#注册中心不需要发现服务
eureka:
  client:
#    register-with-eureka: true
#    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:1111/eureka


