server:
  port: 7080

spring:
  application:
    name: feign-consumer

ribbon:
  eureka:
    enabled: false

calculate:
  ribbon:
    listOfServers: localhost:7070

logging:
  level:
    org.apache.http: trace
